### ISSUE TITLE
Installing "nio" from pip breaks mirage loading?

### ISSUE THREAD

**Issue by koutsie** [mirukana/mirage#107]
### Description

Installing `nio` from pip causes the client to hang on load.

### Your environment
ArchLinux X86_64 (5.7.9-arch1-1)
Installed from AUR with yay.

### Steps to reproduce

1. Install nio
2. Hang on load

### Expected behavior

1. Install nio
2. Not hang on load

### Actual behavior
Client hangs on this screen:
![image](https://user-images.githubusercontent.com/18449778/87850793-9d528980-c8fb-11ea-95d2-8deb664bba2f.png)

with the following error:
```python
~ 13:33:36 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 13:33:36 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```

:shrug:

**Comment by mirukana** [comment]
There should be a longer, more descriptive error message just before the lines you posted, can you paste that?

**Comment by koutsie** [comment]
full stackträäce


```bash
~ 08:41:58 | Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
~ 08:41:58 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 29, in <module>\n    from .pyotherside_events import CoroutineDone, LoopException\n\n  File \"qrc:/src/backend/pyotherside_events.py\", line 8, in <module>\n    from .utils import serialize_value_for_qml\n\n  File \"qrc:/src/backend/utils.py\", line 27, in <module>\n    from nio.crypto import AsyncDataT as File\n\nModuleNotFoundError: No module named 'nio.crypto'\n"
! 08:41:58 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 29, in <module>
    from .pyotherside_events import CoroutineDone, LoopException

  File "qrc:/src/backend/pyotherside_events.py", line 8, in <module>
    from .utils import serialize_value_for_qml

  File "qrc:/src/backend/utils.py", line 27, in <module>
    from nio.crypto import AsyncDataT as File

ModuleNotFoundError: No module named 'nio.crypto'
)
~ 08:41:58 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 08:41:58 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```

**Comment by mirukana** [comment]
You need to install nio with E2E support (as seen in the [requirements.txt](https://github.com/mirukana/mirage/blob/v0.6.0/requirements.txt#L9)), e.g. `pip3 install --user matrix-nio[e2e]`

**Comment by koutsie** [comment]
allrit real odd doe but allright
