### ISSUE TITLE
MatrixError 400 when fetching offline member presence

### ISSUE THREAD

**Issue by theotheroracle** [mirukana/mirage#116]
### Description

error shows when opening rooms

### Your environment

- fedora 32 flatpak

### Steps to reproduce

1. open a room
2. sometimes the error shows up
```
Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 85, in on_done
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1370, in get_offline_presence
    resp = await self.get_presence(user_id)
  File "/app/lib/python3.7/site-packages/nio/client/async_client.py", line 246, in wrapper
    return await func(self, *args, **kwargs)
  File "/app/lib/python3.7/site-packages/nio/client/async_client.py", line 2680, in get_presence
    PresenceGetResponse, method, path, response_data=(user_id,)
  File "qrc:/src/backend/matrix_client.py", line 222, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (400, 'M_UNRECOGNIZED')
```

**Comment by Asherathe** [comment]
I'm using the AppImage version on Peppermint 10 Respin with python 3.8, and I've been getting this error constantly this evening, sometimes directly after restarting Mirage, and sometimes after being in a room for a while. The room it's happening in the most is #aol:chat.weho.st.

**Comment by mirukana** [comment]
https://github.com/mirukana/mirage/commit/32679aa7f8ff426d588e2eb04b6cde5bf1db5ec0 should fix this.
