### ISSUE TITLE
Mirage tries to import Python scripts in current working directory

### ISSUE THREAD

**Issue by HenkKalkwater** [mirukana/mirage#138]
### Description

Describe your issue in details, provide error logs or screenshots if possible.

### Your environment

- OS: OpenSUSE Tumbleweed
- ISA: x86_64
- DE: KDE 5.19.5
- Installation method: Flatpak

### Steps to reproduce

1. Launch Mirage

### Expected behavior

Mirage launches

### Actual behavior

Mirage is stuck on a screen with just a spinner when launched via the installed icon. When I try to run it from the terminal, sometimes it fails, sometimes it doesn't.

Running it from the terminal gives this message:

```
chris@yangchen:~> flatpak run io.github.mirukana.mirage 
~ 21:39:09 | Got library name:  "/app/usr/lib/qml/io/thp/pyotherside/libpyothersideplugin.so"
! 21:39:09 | env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
~ 21:39:10 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 27, in <module>\n    from .pyotherside_events import CoroutineDone, LoopException\n\n  File \"qrc:/src/backend/pyotherside_events.py\", line 8, in <module>\n    from .utils import serialize_value_for_qml\n\n  File \"qrc:/src/backend/utils.py\", line 31, in <module>\n    from nio.crypto import AsyncDataT as File\n\n  File \"/app/lib/python3.7/site-packages/nio/__init__.py\", line 2, in <module>\n    from .client import *\n\n  File \"/app/lib/python3.7/site-packages/nio/client/__init__.py\", line 3, in <module>\n    from .base_client import Client, ClientConfig\n\n  File \"/app/lib/python3.7/site-packages/nio/client/base_client.py\", line 35, in <module>\n    from ..crypto import ENCRYPTION_ENABLED\n\n  File \"/app/lib/python3.7/site-packages/nio/crypto/__init__.py\", line 41, in <module>\n    from .olm_machine import Olm\n\n  File \"/app/lib/python3.7/site-packages/nio/crypto/olm_machine.py\", line 54, in <module>\n    from .sas import Sas\n\n  File \"/app/lib/python3.7/site-packages/nio/crypto/sas.py\", line 26, in <module>\n    from future.moves.itertools import zip_longest\n\n  File \"/app/lib/python3.7/site-packages/future/moves/__init__.py\", line 8, in <module>\n    import_top_level_modules()\n\n  File \"/app/lib/python3.7/site-packages/future/standard_library/__init__.py\", line 810, in import_top_level_modules\n    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):\n\n  File \"/app/lib/python3.7/site-packages/future/standard_library/__init__.py\", line 781, in __enter__\n    module = __import__(m, level=0)\n\n  File \"/home/chris/test.py\", line 5, in <module>\n    with open(dir + 'current_avg', 'r') as f:\n\nFileNotFoundError: [Errno 2] Bestand of map bestaat niet: '/sys/class/power_supply/max170xx_battery/current_avg'\n"
! 21:39:10 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 27, in <module>
    from .pyotherside_events import CoroutineDone, LoopException

  File "qrc:/src/backend/pyotherside_events.py", line 8, in <module>
    from .utils import serialize_value_for_qml

  File "qrc:/src/backend/utils.py", line 31, in <module>
    from nio.crypto import AsyncDataT as File

  File "/app/lib/python3.7/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *

  File "/app/lib/python3.7/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig

  File "/app/lib/python3.7/site-packages/nio/client/base_client.py", line 35, in <module>
    from ..crypto import ENCRYPTION_ENABLED

  File "/app/lib/python3.7/site-packages/nio/crypto/__init__.py", line 41, in <module>
    from .olm_machine import Olm

  File "/app/lib/python3.7/site-packages/nio/crypto/olm_machine.py", line 54, in <module>
    from .sas import Sas

  File "/app/lib/python3.7/site-packages/nio/crypto/sas.py", line 26, in <module>
    from future.moves.itertools import zip_longest

  File "/app/lib/python3.7/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()

  File "/app/lib/python3.7/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):

  File "/app/lib/python3.7/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)

  File "/home/chris/test.py", line 5, in <module>
    with open(dir + 'current_avg', 'r') as f:

FileNotFoundError: [Errno 2] Bestand of map bestaat niet: '/sys/class/power_supply/max170xx_battery/current_avg'
)
~ 21:39:10 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 21:39:10 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
```

**Comment by HenkKalkwater** [comment]
Okay, apparently Python likes to look for modules its the working directory, which explains why `/home/chris/test.py` gets loaded. When I execute Mirage in any other directory than my home directory, it works, because the test.py file is absent there.

test.py was something I wrote to quickly test out reading my current charge level, I forgot about that file and left it lingering in my home directory. I guess I could remove that file and close this issue, but I'd like to suggest that maybe it could be useful to prevent the bundled Python from loading modules in its working directory in the first place. It is prepackaged software, so it shouldn't try to load modules from its working directory. It could potentially be abused if a malicious program placed shady Python files into my home directory which could hijack the program.

**Comment by mirukana** [comment]
Looks like https://github.com/PythonCharmers/python-future/issues/268, I'll see if I can implement a workaround for this. Until then, you can probably just rename `test.py` to something that library doesn't try to import, like `test1.py`?

**Comment by HenkKalkwater** [comment]
Ah, that makes more sense. I've never encountered this before, but I have written some Python scripts into my home directory. It seems that's just a module that's misbehaving in this case, not Python doing things wrong.

If its a known issue with a library, in my opinion, you shouldn't have try to work around it in Mirage. Just nag the python-future developers a tad more :), so they can fix it. You can close this issue if you want to.

In the meanwhile, I have renamed the file, which works fine.

**Comment by mirukana** [comment]
I looked a bit more, I doubt it's something they can fix since it's the normal Python behavior: a library tries to import the standard module named `test`, but the current folder has higher priority in `sys.path`.
