### ISSUE TITLE
NameError: name 'BRIDGE' is not defined

### ISSUE THREAD

**Issue by babolivier** [mirukana/mirage#15]
Running `mirage` right after installing it on my Archlinux setup causes an infinite spinner and prints the following in the following to be printed in the terminal:

```
Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"src/backend/qml_bridge.py\", line 148, in <module>\n    BRIDGE = QMLBridge()\n\n  File \"src/backend/qml_bridge.py\", line 43, in __init__\n    from .backend import Backend\n\n  File \"src/backend/backend.py\", line 15, in <module>\n    from .matrix_client import MatrixClient\n\n  File \"src/backend/matrix_client.py\", line 39, in <module>\n    from .media_cache import Media, Thumbnail\n\n  File \"src/backend/media_cache.py\", line 30, in <module>\n    CONCURRENT_DOWNLOADS_LIMIT                   = asyncio.BoundedSemaphore(8)\n\n  File \"/usr/lib/python3.8/asyncio/locks.py\", line 529, in __init__\n    super().__init__(value, loop=loop)\n\n  File \"/usr/lib/python3.8/asyncio/locks.py\", line 458, in __init__\n    self._loop = events.get_event_loop()\n\n  File \"/usr/lib/python3.8/asyncio/events.py\", line 639, in get_event_loop\n    raise RuntimeError('There is no current event loop in thread %r.'\n\nRuntimeError: There is no current event loop in thread 'Dummy-1'.\n"
Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "src/backend/qml_bridge.py", line 148, in <module>
    BRIDGE = QMLBridge()

  File "src/backend/qml_bridge.py", line 43, in __init__
    from .backend import Backend

  File "src/backend/backend.py", line 15, in <module>
    from .matrix_client import MatrixClient

  File "src/backend/matrix_client.py", line 39, in <module>
    from .media_cache import Media, Thumbnail

  File "src/backend/media_cache.py", line 30, in <module>
    CONCURRENT_DOWNLOADS_LIMIT                   = asyncio.BoundedSemaphore(8)

  File "/usr/lib/python3.8/asyncio/locks.py", line 529, in __init__
    super().__init__(value, loop=loop)

  File "/usr/lib/python3.8/asyncio/locks.py", line 458, in __init__
    self._loop = events.get_event_loop()

  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'Dummy-1'.
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```

**Comment by mirukana** [comment]
Can you the [event-loop-fix](https://github.com/mirukana/mirage/tree/event-loop-fix) branch to see if it fixes the issue?

**Comment by babolivier** [comment]
Right, I think I figured it out - looks like it was because I installed everything in a virtualenv.
I've re-run the install process outside of it and it works fine now.

**Comment by Amolith** [comment]
Mirage is crashing for me as well and I get a somewhat similar traceback; I didn't think it warranted its own issue because it looks like the core problem is the same. I installed it with the [AUR package](https://aur.archlinux.org/packages/matrix-mirage-git/).
```
❯ mirage
Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 19, in <module>\n    from .pyotherside_events import CoroutineDone, LoopException\n\n  File \"qrc:/src/backend/pyotherside_events.py\", line 8, in <module>\n    from .utils import serialize_value_for_qml\n\n  File \"qrc:/src/backend/utils.py\", line 24, in <module>\n    import filetype\n\nModuleNotFoundError: No module named 'filetype'\n"
Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 19, in <module>
    from .pyotherside_events import CoroutineDone, LoopException

  File "qrc:/src/backend/pyotherside_events.py", line 8, in <module>
    from .utils import serialize_value_for_qml

  File "qrc:/src/backend/utils.py", line 24, in <module>
    import filetype

ModuleNotFoundError: No module named 'filetype'
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
```

**Comment by mirukana** [comment]
Can you post the output of these?

    python3 -c 'import filetype; print(filetype)'

And in `<mirage repo root>/src/backend/qml_bridge.py`, add this to the top before any `import` statement:
    
    import sys; print(sys.path)

Then start mirage with:

    make clean; qmake mirage.pro CONFIG+= dev && make && ./mirage

**Comment by DataBeaver** [comment]
I got the error mentioned in the original report and also had some Python packages installed in virtualenv (those not available in Debian unstable).  I'm not sure how virtualenv affects it, but there seems to be something funny about threads.  Apparently the Python bridge thread is not the main application thread so the asyncio module does not install a default event loop.  I was able to fix it with:

```
--- a/src/backend/qml_bridge.py
+++ b/src/backend/qml_bridge.py
@@ -25,6 +25,11 @@ except ModuleNotFoundError:
 else:
     uvloop.install()
 
+try:
+    asyncio.get_event_loop()
+except RuntimeError:
+    asyncio.set_event_loop(asyncio.new_event_loop())
+
 
 class QMLBridge:
     """Setup asyncio and provide synchronous methods to call coroutines.
```

However I'm then getting a bunch of various QML errors and messages are not displayed, but I think that's a different issue.

**Comment by mirukana** [comment]
The error shouldn't be the same unless you run an old version of Mirage, can you post the full traceback? 
`QMLBridge.__init__()` does start a thread, and an asyncio loop is created inside to handle coroutine calls from QML, so it wouldn't make sense to create one before the class like this.

**Comment by DataBeaver** [comment]
```
Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 153, in <module>
    BRIDGE = QMLBridge()

  File "qrc:/src/backend/qml_bridge.py", line 48, in __init__
    from .backend import Backend

  File "qrc:/src/backend/backend.py", line 15, in <module>
    from .matrix_client import MatrixClient

  File "qrc:/src/backend/matrix_client.py", line 40, in <module>
    from .media_cache import Media, Thumbnail

  File "qrc:/src/backend/media_cache.py", line 30, in <module>
    CONCURRENT_DOWNLOADS_LIMIT                   = asyncio.BoundedSemaphore(8)

  File "/usr/lib/python3.8/asyncio/locks.py", line 529, in __init__
    super().__init__(value, loop=loop)

  File "/usr/lib/python3.8/asyncio/locks.py", line 458, in __init__
    self._loop = events.get_event_loop()

  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'Dummy-1'.
```

QMLBridge.__init__ does not explicitly create an asyncio event loop; it relies on get_event_loop implicitly creating one.  According to [the documentation](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) that only happens if the OS thread is main, which apparently is not the case here.  Using strace I can see that the process starts with pid 24064 but the exception gets printed from pid 24066.

Furthermore, as can be seen in the traceback, a few calls down from the import Backend line there's an attempt to create a semaphore, which wants to attach itself to the event loop of the current thread.  This happens before even the get_event_loop call in QMLBridge.__init__.

My patch attempts to do the same get_event_loop() call and if it doesn't succeed, it explicitly creates a new event loop and sets it for the current thread.  The exact placement of these lines does not really matter as long as they happen before the import Backend call.  Here's an alternative version:

```
--- a/src/backend/qml_bridge.py
+++ b/src/backend/qml_bridge.py
@@ -40,12 +40,16 @@ class QMLBridge:
     """
 
     def __init__(self) -> None:
+        try:
+            self._loop = asyncio.get_event_loop()
+        except RuntimeError:
+            self._loop = asyncio.new_event_loop()
+            asyncio.set_event_loop(self._loop)
+        self._loop.set_exception_handler(self._loop_exception_handler)
+
         from .backend import Backend
         self.backend: Backend = Backend()
 
-        self._loop = asyncio.get_event_loop()
-        self._loop.set_exception_handler(self._loop_exception_handler)
-
         Thread(target=self._start_asyncio_loop).start()
 
 
```

My version of Mirage is git version from Monday, with HEAD at 8b8829a.

**Comment by mirukana** [comment]
You're right, I didn't even notice the `import Backend`'s position until now.
As noted by the `FIXME` comment at the bottom of `qml_bridge.py`, it seems like the thread behavior is inconsistent between different versions of python. Even stranger, I've upgraded to Python 3.8 recently and I get that problem with signals but not the one you're talking about. 

In any case, if your issue #35 is fixed, is everything working with your patch? Will you make a PR, or should I just add the changes myself?

**Comment by DataBeaver** [comment]
I haven't tried any advanced features yet but now that I got #35 fixed I can at least get a working UI and view channels.

**Comment by zacharytyhacz** [comment]
I just updated my arch linux, and mirage just broke with this exact error message. What broke?

**Comment by zacharytyhacz** [comment]
Here is full log from starting mirage with the command `$ mirage` 
```bash
~ 11:04:06 | Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyo
~ 11:04:07 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 176, in <module>\n    BRIDGE = QMLBridge()\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 53, in __init__\n    from .backend import Backend\n\n  File \"qrc:/src/backend/backend.py\", line 17, in <module>\n    from .matrix_client import MatrixClient\n\n  File \"qrc:/src/backend/matrix_client.py\", line 42, in <module>\n    from .html_markdown import HTML_PROCESSOR as HTML\n\n  File \"qrc:/src/backend/html_markdown.py\", line 9, in <module>\n    import html_sanitizer.sanitizer as sanitizer\n\nModuleNotFoundError: No module named 'html_sanitizer'\n"
! 11:04:07 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 176, in <module>
    BRIDGE = QMLBridge()

  File "qrc:/src/backend/qml_bridge.py", line 53, in __init__
    from .backend import Backend

  File "qrc:/src/backend/backend.py", line 17, in <module>
    from .matrix_client import MatrixClient

  File "qrc:/src/backend/matrix_client.py", line 42, in <module>
    from .html_markdown import HTML_PROCESSOR as HTML

  File "qrc:/src/backend/html_markdown.py", line 9, in <module>
    import html_sanitizer.sanitizer as sanitizer

ModuleNotFoundError: No module named 'html_sanitizer'
)
~ 11:04:07 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 11:04:07 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)

```


I am on arch linux, and I guess an update with python somewhere changed some python sym links ( weird python version sym linking )

I reinstalled `python2` and `python2-pip` ( not entirely sure if this did anything ) 
and then I did: `$ python3 -m pip install html_sanitizer` and now it is working. I am not sure what happened, but I think it had something to do with pointing to the wrong python version due to my messed up python version sym linking
