### ISSUE TITLE
Unexpected error occured: DBusException

### ISSUE THREAD

**Issue by ISSOtm** [mirukana/mirage#169]
### Description

```
desktop_notify.f01143b5-a1d3-4628-944b-50f7d53420bd

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "qrc:/src/backend/backend.py", line 555, in desktop_notify
    plyer.notification.notify(
  File "/usr/lib/python3.9/site-packages/plyer/facades/notification.py", line 79, in notify
    self._notify(
  File "/usr/lib/python3.9/site-packages/plyer/platforms/linux/notification.py", line 44, in _notify
    obj = session_bus.get_object(_bus_name, _object_path)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

Occurs every time a message is posted while Mirage is not focused.

### Your environment

- Arch Linux
- x86_64
- i3 version 4.19 (2020-11-15)
- Installed via [matrix-mirage-git on AUR](https://aur.archlinux.org/packages/matrix-mirage-git/), package version `r2411.dea827b3-1` (Mirage reports "0.6.4")

### Steps to reproduce

1. Focus another window
2. Have someone else send a message

### Expected behavior

Nothing.

### Actual behavior

An error box pops up with the error message pasted at the top of this issue.

**Comment by vSLG** [comment]
Do you have any notification server installed (e.g. `dunst`)?

**Comment by ISSOtm** [comment]
Not as far as I'm aware.

**Comment by mirukana** [comment]
This error happens if you don't have dbus running, which is started either manually, with a service, or by a notification server. Unfortunately, dbus the only way to create "native" Linux notifications, but I guess we can implement a fallback system with notification windows drawn by the app if the normal method isn't available on the system.

**Comment by ISSOtm** [comment]
DBus *is* running (`dbus.service` is `active (running)`), I just don't have anything listening for notifications.

As far as I'm concerned, simply catching and dismissing the exception would be enough. I'm fine with not getting notifications, I just don't want to have to dismiss dozens of error popups when a conversation happens while I'm not focusing the window.
