### ISSUE TITLE
"Invalid request or login type" when trying to sign in

### ISSUE THREAD

**Issue by rex4539** [mirukana/mirage#19]
Latest master.

Reproducibility: always

Steps:
Enter username and password, then sign in.

What happened:
<img width="1264" alt="Screen Shot 2020-03-28 at 22 47 09" src="https://user-images.githubusercontent.com/227442/77833454-1d36c700-7146-11ea-9ef8-3c98cb49375d.png">

Expected result:
Logging in is successful.

**Comment by mirukana** [comment]
I've pushed a commit to master that make that kind of failed login show error details in both the GUI and the starting terminal, can you try it and report the traceback?

**Comment by rex4539** [comment]
```
2020-03-29 18:52:32.527361+0300 mirage[30851:5600061] [qml] python: login_client.7ae9a5c6-22ee-4a3d-821a-7400cc6e8c8d
Traceback (most recent call last):
  File "src/backend/qml_bridge.py", line 78, in on_done
    result = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "src/backend/backend.py", line 113, in login_client
    await client.login(password)
  File "src/backend/matrix_client.py", line 176, in login
    password, device_name or self.default_device_name(),
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/async_client.py", line 684, in login
    return await self._send(LoginResponse, method, path, data)
  File "src/backend/matrix_client.py", line 149, in _send
    response = await super()._send(*args, **kwargs)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/async_client.py", line 583, in _send
    await self.receive_response(resp)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/async_client.py", line 516, in receive_response
    super().receive_response(response)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 899, in receive_response
    self._handle_login(response)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 541, in _handle_login
    self.load_store()
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 315, in load_store
    raise LocalProtocolError("No store class was provided in the "
nio.exceptions.LocalProtocolError: No store class was provided in the config.
```

**Comment by mirukana** [comment]
What does the `python3 -c 'import nio; print(nio.crypto.ENCRYPTION_ENABLED)'` return?

**Comment by rex4539** [comment]
```
% python3 -c 'import nio; print(nio.crypto.ENCRYPTION_ENABLED)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 25, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/crypto/__init__.py", line 23, in <module>
    from .sessions import (
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/crypto/sessions.py", line 24, in <module>
    import olm
  File "/Library/Python/3.7/site-packages/python_olm-3.1.4-py3.7-macosx-10.14-x86_64.egg/olm/__init__.py", line 24, in <module>
    from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
  File "/Library/Python/3.7/site-packages/python_olm-3.1.4-py3.7-macosx-10.14-x86_64.egg/olm/utility.py", line 39, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: dlopen(/Library/Python/3.7/site-packages/python_olm-3.1.4-py3.7-macosx-10.14-x86_64.egg/_libolm.abi3.so, 2): Library not loaded: build/libolm.dylib.3.1.4
  Referenced from: /Library/Python/3.7/site-packages/python_olm-3.1.4-py3.7-macosx-10.14-x86_64.egg/_libolm.abi3.so
  Reason: image not found
```

**Comment by mirukana** [comment]
Seems like it's the same issue as this: https://github.com/poljar/matrix-nio/issues/49
I unfortunately can't provide any help on that since I don't have a mac, but you can try pursuing the discussion on the nio issue.

**Comment by rex4539** [comment]
ok, I got some progress.

I manually installed olm python bindings so now I get this:
```
% python3 -c 'import nio; print(nio.crypto.ENCRYPTION_ENABLED)'
True
```

But in the login screen, I still get:
```
2020-03-29 21:29:20.992009+0300 mirage[43595:5886308] [qml] python: login_client.13c42529-c55a-4127-b189-1d7052b6dfb0
Traceback (most recent call last):
  File "src/backend/qml_bridge.py", line 78, in on_done
    result = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "src/backend/backend.py", line 113, in login_client
    await client.login(password)
  File "src/backend/matrix_client.py", line 176, in login
    password, device_name or self.default_device_name(),
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/async_client.py", line 684, in login
    return await self._send(LoginResponse, method, path, data)
  File "src/backend/matrix_client.py", line 149, in _send
    response = await super()._send(*args, **kwargs)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/async_client.py", line 583, in _send
    await self.receive_response(resp)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/async_client.py", line 516, in receive_response
    super().receive_response(response)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 899, in receive_response
    self._handle_login(response)
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 541, in _handle_login
    self.load_store()
  File "/Users/rex/Library/Python/3.7/lib/python/site-packages/nio/client/base_client.py", line 315, in load_store
    raise LocalProtocolError("No store class was provided in the "
nio.exceptions.LocalProtocolError: No store class was provided in the config.
```

**Comment by clouetb** [comment]
Hi, I got around this issue. Have a look at my fix here poljar/matrix-nio#49 and let me know if it works.

**Comment by rex4539** [comment]
@clouetb I already managed to olm and nio. My problem is I cannot login to mirage.

**Comment by clouetb** [comment]
@rex4539 sorry, I did not notice that you faced now a different issue.

**Comment by mirukana** [comment]
@rex4539 Does this still happen on the new release?

**Comment by rex4539** [comment]
Yes. I have never been able to log in with this client.

**Comment by mirukana** [comment]
Can you post the result of `python3 -c 'import nio; print(nio.__file__)'`?

Then, start Mirage from a terminal, press alt+shift+D to start the python debugger in the terminal, and post the result of these commands:
```
import nio
nio.__file__
nio.crypto.ENCRYPTION_ENABLED
```

**Comment by rex4539** [comment]
I give up :)
