### ISSUE TITLE
Error when forwarding unencrypted image in encrypted room

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#202]
### Description

Unencrypted images can be sent in encrypted rooms, for example by using the forwarding feature in Element of Fluffychat. Mirage does not recognize these images.
![](https://f.mazie.rocks/Screenshot_2021-03-29_17-43-51.png)
![](https://f.mazie.rocks/Screenshot_2021-03-29_17-40-16.png)

### Your environment

- OS or distribution: Arch Linux
- Architecture: 64 bit
- desktop environment or window manager: Awesome wm v4.3
- How did you install Mirage? `yay -S matrix-mirage-git` (installed from AUR but from source)
- Qt version: 5.15.2
- Python version: 3.9.2

### Steps to reproduce

1. Send any image in an unencrypted room
2. Open this unencrypted room in Element, click `...` and `Forward Message`. Then pick an encrypted room.
3. The image will be sent in the encrypted room.
4. Open this encrypted room in Mirage and see that the image fails to display.

### Expected behavior

Image should display.

### Actual behavior

Image does not display and I got this error:

```
'BadEvent' object has no attribute 'flattened'

Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 410, in _start
    await self.sync_task
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 1181, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 262, in _send
    response = await super()._send(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 774, in _send
    await self.receive_response(resp)
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 689, in receive_response
    await self._handle_sync(response)
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 656, in _handle_sync
    await self._handle_joined_rooms(response)
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 583, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
  File "qrc:/src/backend/nio_callbacks.py", line 675, in onBadEvent
    await self.client.register_nio_event(room, ev, content=co)
  File "qrc:/src/backend/matrix_client.py", line 2451, in register_nio_event
    nio_rule = self.push_rules.global_rules.matching_rule(ev, room, name)
  File "/usr/lib/python3.9/site-packages/nio/events/account_data.py", line 527, in matching_rule
    if rule.matches(event, room, display_name):
  File "/usr/lib/python3.9/site-packages/nio/events/account_data.py", line 472, in matches
    return all(c.matches(event, room, display_name) for c in conditions)
  File "/usr/lib/python3.9/site-packages/nio/events/account_data.py", line 472, in <genexpr>
    return all(c.matches(event, room, display_name) for c in conditions)
  File "/usr/lib/python3.9/site-packages/nio/events/account_data.py", line 184, in matches
    value = event.flattened().get(self.key)
AttributeError: 'BadEvent' object has no attribute 'flattened'
```

**Comment by mirukana** [comment]
Caused by https://github.com/poljar/matrix-nio/issues/224

**Comment by MRAAGH** [comment]
Possible duplicate of #159
