### ISSUE TITLE
Sudden Matrix error when idle

### ISSUE THREAD

**Issue by samyak-jain** [mirukana/mirage#212]
### Description

Mirage was simply running in the foreground and the following error popped up. 

```
(200, None)

Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 410, in _start
    await self.sync_task
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 1181, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 266, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)
```

![matrix-error](https://user-images.githubusercontent.com/10133258/114501651-04615c80-9c48-11eb-9632-bd946ed08be8.png)

### Your environment

- OS or distribution (e.g. Arch Linux, macOS 10.15, Windows 7...): 5.11.12-arch1-1
- Architecture (e.g. x86 64bit): x86_64
- For Linux users: your desktop environment or window manager (e.g. GNOME 3.34 Wayland, i3 4.17, etc): bspwm
- How did you install Mirage? (e.g. manual build, distribution repository, AppImage, Flatpak...): AUR
- For manual installations: your Qt version
- For manual installations: your Python version

**Comment by mirukana** [comment]
Some details needed to identify the problem were lacking from the error popup in the version you ran. Please update to the [last dev commit](https://github.com/mirukana/mirage/commit/b9f34dd81073a1981df57db9a21f61cdd0433f60) (the mirage -git AUR package should have it) and post the error if this occurs again.

**Comment by zapashcanon** [comment]
I built mirage from source, and here's what I get:

```txt
(200, None)

Traceback (most recent call last):
  File "src/backend/matrix_client.py", line 410, in _start
    await self.sync_task
  File "/home/zapashcanon/.local/lib/python3.9/site-packages/nio/client/async_client.py", line 1155, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/home/zapashcanon/.local/lib/python3.9/site-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "src/backend/matrix_client.py", line 266, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)
```

But that doesn't seem to bring much more information, so I'm wondering if I did something wrong...

**Comment by mirukana** [comment]
Make sure you're on the right branch, run `git checkout dev` before building.

**Comment by zapashcanon** [comment]
Ah indeed, that whas it. Thanks. Now I get a huge error, here's the beginning:

```txt
MatrixError: (200, None, 'unknown error', '{"next_batch":"
```

But what comes after is full of personal information that I don't want to share here and it's so huge that I don't want to filter it. Could you [contact me](https://www.zapashcanon.fr/contact.html) and I'll send you the file ?

**Comment by dwho123** [comment]
I also have this issue and it prevents the affected account's rooms from even loading (matrix.org and chatcloud.net). It has been a pain, because I made that chatcloud account to deal with the first matrix.org account breaking. Don't feel like making anymore new accounts after the second time, so I have to stick with talking to my friend from Element mobile. ><

**Comment by mirukana** [comment]
This should fixed by https://github.com/poljar/matrix-nio/commit/1f17a20ca818c1c3a0c2e75fdc64da9c629eb5f9. This commit will be part of matrix-nio 0.18.5, which is to be officially released before tomorrow. It already is included in the new mirage 0.7.2 appimage and flatpaks. For manual installs, make sure to run `pip3 install --user -Ur requirements.txt` again before rebuilding.

**Comment by redianthus** [comment]
@mirukana this is fixed for me ! Thanks. :-)
