### ISSUE TITLE
Failure to sync after restart

### ISSUE THREAD

**Issue by goodboy** [mirukana/mirage#218]
### Description

`mirage` starts up great on initial run and after sign-in to homeserver works as expected.
Upon restarting the client it fails to sync with the following python error which spins indefinitely:

```python

X 09:19:51 | python:
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 415, in _start
    await self.sync_task
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 1155, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 269, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (400, 'M_UNKNOWN')
^CINFO:root:Setting clients offline...
(400, 'M_UNKNOWN')
```

### Your environment
AUR package:

```
>>> aura -Qi matrix-mirage-git
Name            : matrix-mirage-git
Version         : r2617.83a59644-1
Description     : A fancy, customizable, keyboard-operable Matrix chat client for
                  encrypted and decentralized communication.
Architecture    : any
URL             : https://github.com/mirukana/mirage
Licenses        : LGPL3
Groups          : None
Provides        : None
Depends On      : qt5-base  qt5-declarative  qt5-quickcontrols2  qt5-svg
                  qt5-graphicaleffects  qt5-imageformats  python  python-pyotherside
                  libolm  libjpeg-turbo  zlib  libtiff  libwebp  openjpeg2  libmediainfo
                  python-pillow  python-pymediainfo  python-cairosvg  python-aiofiles
                  python-appdirs  python-filetype  python-html-sanitizer  python-lxml
                  python-mistune  python-blist  python-matrix-nio>=0.17.0  libxss
                  python-plyer  python-sortedcontainers  python-watchgod  python-redbaron
                  python-dbus  python-hsluv  python-pycryptodome  python-simpleaudio
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : mirage-matrix  matrix-mirage
Replaces        : None
Installed Size  : 1061.83 KiB
Packager        : Unknown Packager
Build Date      : Mon Apr 19 08:45:05 2021
Install Date    : Mon Apr 19 08:52:11 2021
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

- i3, 5.11.14 kernel, AUR install (yikes!)

### Steps to reproduce

1. start and sign in
2. close
2. start

### Expected behavior

`mirage` starts up without error.

**Comment by mirukana** [comment]
Should be fixed by 888e240b8f714b623fc7b1bae4961e8bdbec6d52
