### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by zapashcanon** [mirukana/mirage#220]
Hi,

Mirage was open and suddenly I got an error message. Whenever I try to restart mirage, I got this:

```
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1130, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1003, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 251, in _send
    response = await super()._send(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 717, in _send
    resp = await self.create_matrix_response(
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 504, in create_matrix_response
    resp = response_class.from_dict(parsed_dict, *data)
  File "/usr/lib/python3/dist-packages/nio/responses.py", line 170, in wrapper
    return f(cls, parsed_dict, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/nio/responses.py", line 1745, in from_dict
    rooms = SyncResponse._get_room_info(parsed_dict["rooms"])
  File "/usr/lib/python3/dist-packages/nio/responses.py", line 1688, in _get_room_info
    for room_id, room_dict in parsed_dict["invite"].items():
KeyError: 'invite'
```

Also, someone (@RadioPotin) I was talking with on mirage when it happened got the same error simultaneously.

I'm running debian unstable with mirage from debian repository Version: 0.11.1-1+b2, I'm using sway and thus wayland.

**Comment by mirukana** [comment]
Fixed in https://github.com/poljar/matrix-nio/commit/c52b3d139495c1b6dc56a7f9f3b3582cdacc59f8, this should land in the next version of the matrix-nio dependency.

**Comment by zapashcanon** [comment]
Thanks !

**Comment by zapashcanon** [comment]
@mirukana I patched directly the file to get a working mirage without waiting for the new release to land in Debian. It works better but I now have a new error :

```txt

Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1130, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1003, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)
```

**Comment by mirukana** [comment]
See https://github.com/mirukana/mirage/issues/212
