### ISSUE TITLE
Installing from AUR does't work

### ISSUE THREAD

**Issue by sTiKyt** [mirukana/mirage#221]
Installed packege from AUR, got endless loading screen and error messages in result:
![image](https://user-images.githubusercontent.com/35602029/117862707-a1410500-b29b-11eb-9500-2374a279ab15.png)

```
~ 20:57:22 | Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
! 20:57:22 | QSystemTrayIcon::setVisible: No Icon set
/usr/lib/python3.9/site-packages/baron/grammator.py:830: ParserGeneratorWarning: Token 'EXEC' is unused
  parser = pg.build()
~ 20:57:24 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 181, in <module>\n    BRIDGE = QMLBridge()\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 52, in __init__\n    from .backend import Backend\n\n  File \"qrc:/src/backend/backend.py\", line 28, in <module>\n    from .matrix_client import MatrixClient\n\n  File \"qrc:/src/backend/matrix_client.py\", line 42, in <module>\n    from .html_markdown import HTML_PROCESSOR as HTML\n\n  File \"qrc:/src/backend/html_markdown.py\", line 11, in <module>\n    import html_sanitizer.sanitizer as sanitizer\n\nModuleNotFoundError: No module named 'html_sanitizer'\n"
! 20:57:24 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 181, in <module>
    BRIDGE = QMLBridge()

  File "qrc:/src/backend/qml_bridge.py", line 52, in __init__
    from .backend import Backend

  File "qrc:/src/backend/backend.py", line 28, in <module>
    from .matrix_client import MatrixClient

  File "qrc:/src/backend/matrix_client.py", line 42, in <module>
    from .html_markdown import HTML_PROCESSOR as HTML

  File "qrc:/src/backend/html_markdown.py", line 11, in <module>
    import html_sanitizer.sanitizer as sanitizer

ModuleNotFoundError: No module named 'html_sanitizer'
)
~ 20:57:24 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 20:57:24 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```

Tried both `matrix-mirage` and `matrix-mirage-git`

**Comment by SIR-unit** [comment]
I had this problem and I was able to work around it by recursively launching mirage and installing the missing packages, i.e.:
`pip install plyer simpleaudio html_sanitizer`
You should probably do this as a user or in a python virtual environment (see python venv).

**Comment by sTiKyt** [comment]
> I had this problem and I was able to work around it by recursively launching mirage and installing the missing packages, i.e.:
> `pip install plyer simpleaudio html_sanitizer`
> You should probably do this as a user or in a python virtual environment (see python venv).

I think AUR package should do it, as it's supposed to automate installation process

**Comment by SIR-unit** [comment]
Yes it is supposed to.  However it does not which is why this is a bug :)
You can wait for them to patch it in the AUR, or patch it manually with my fix.  I just happened to have the same problem and was letting people know what is wrong

**Comment by mirukana** [comment]
I think this is fixed? https://aur.archlinux.org/packages/matrix-mirage-git/ lists `html_sanitizer` and others in the dependencies. If the issue is really a distro's package, it should be raised on that distro's site/to that package's maintainer, as I have no control over them.
