### ISSUE TITLE
ContentTypeError on 'https://www.anchel.nl/'

### ISSUE THREAD

**Issue by JulienPalard** [mirukana/mirage#249]
### Description

When I start Mirage for the first time, I'm getting a flood of:

```
Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 83, in on_done
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "qrc:/src/backend/backend.py", line 516, in fetch_homeservers
    for server in (await response.json()):
  File "/usr/lib/python3/dist-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.anchel.nl/')
```

### Your environment

- Debian Bookworm
- x86_64
- i3wm 4.19
- apt (got matrix-mirage 0.6.4), tried it using a local build from commit 9a4ababd9aa59bd78ad239422918c2c4eaaf6b7d (current HEAD) and it happen too.
- 5.15.2
- 3.9.2

### Steps to reproduce

Open a terminal and either run `matrix-mirage` (if installed from apt) or `./mirage` (if compiled locally but not installed).

### Expected behavior

To see a list of homeservers I bet?

### Actual behavior

The list remains empty, an infinite loading wheel loads, and I'm getting the exception continuously on stderr.

**Comment by JulienPalard** [comment]
Looked at it, `backend.py:554` have:

> api_list = "https://publiclist.anchel.nl/publiclist.json"

but:
```
$ curl -I 'https://publiclist.anchel.nl/publiclist.json'
HTTP/2 302 
[...]
location: https://www.anchel.nl/
```

**Comment by MoKe12g** [comment]
Mirage seems to expect this https://web.archive.org/web/20210125045823/https://publiclist.anchel.nl/publiclist.json
I reuploaded it to use it temporarily (after replacing the archive urls to the normal ones) to pastebin https://pastebin.com/raw/t5HQ13Zd
After replacing the url in `backend.py:554` there are still parsing errors.
Did i do something wrong?

``` 21:30:10 | Traceback (most recent call last):
  File "src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "src/backend/backend.py", line 558, in fetch_homeservers
    for server in (await response.json()):
  File "/home/user/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://pastebin.com/raw/t5HQ13Zd')
```

**Comment by JulienPalard** [comment]
This is not a parse error, this is just the HTTP library whining about the content-type not being application/json while you ask for it to be json decoded.

There should be an argument to the `json()` function of this library to tell "text/plain" is OK and you know what's you're doing.
