### ISSUE TITLE
backend.errors.MatrixError: (200, None)

### ISSUE THREAD

**Issue by JulienPalard** [mirukana/mirage#250]
### Description

I'm getting a exception every few seconds after logging-in.

### Your environment

- OS or distribution: mobian (Debian bookworm)
- Architecture: aarch64
- For Linux users: your desktop environment or window manager: phosh 0.13
- How did you install Mirage? `apt install matrix-mirage` (got `0.6.4~dfsg+~hsluv1.0.0-4`)

### Steps to reproduce

Start `matrix-mirage` (login to a homeserver is not already done).

### Expected behavior

I expect the list of chan to appear.

### Actual behavior

I see my avatar, but every 5 seconds the following exception pops:
```
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1130, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1003, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)
```

According to my homeserver logs it's the following request:

```
2021-08-27 00:23:35,667 - synapse.access.http.8008 - 389 - INFO - GET-2246- 127.0.0.1 - 8008 - {@julien:palard.fr} Processed request: 0.197sec/-0.001sec (0.147sec, 0.006sec) (0.450sec/0.109sec/21) 12854B 200 "GET /_matrix/client/r0/sync?access_token=<redacted>&set_presence=online&filter=1 HTTP/1.0" "Python/3.9 aiohttp/3.7.4" [0 dbevts]
```

I'm also using mirage from a Debian desktop (x86_64) (exact same version of mirage, from the same repositories, same homeserver, same account) and it works.

Differences I see:

When my desktop does the requests (when it works), the server keep the connection (does long pooling?) 10s, but when my phone make the requests, they are closed after like 0.2s.

I tried playing the request using curl and it goes OK as far as I can tell: it gives:

```
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Thu, 26 Aug 2021 22:46:13 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date
Strict-Transport-Security: max-age=63072000; always
```

followed by 47KB of valid json.

**Comment by JulienPalard** [comment]
After an `apt upgrade` this morning, giving me:

- python3-matrix-nio 0.18.6-1 (previously: 0.16.0-1)
- python3-aiohttp-socks 0.5.3-1

it works \o/
