### ISSUE TITLE
Homeserver list screen glitches and shows infinite spinner when publiclist.anchel.nl is down

### ISSUE THREAD

**Issue by bbhtt** [mirukana/mirage#262]
### Description

[publiclist.anchel.nl](https://web.archive.org/web/20210525055137/http://publiclist.anchel.nl/) seems to be down at the moment, I assume the same will happen if it is blocked or fails to resolve (dns blocklist, firewall etc.). In this situation the homeserver list screen of Mirage glitches and shows an infinite spinner which is visually confusing. Along with that, it creates endless output on terminal:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "qrc:/src/backend/backend.py", line 555, in fetch_homeservers
    response = await session.get(api_list)
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 244, in connect_wrapper
    connection = await type(self).connect(self, *args, **kwargs)
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/user/Downloads/squashfs-root/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host publiclist.anchel.nl:443 ssl:default [Name or service not known]
```
### Your environment

- OS or distribution: Arch Linux
- Architecture: 64bit
- DE: GNOME/Wayland
- Installation method: AppImage

### Steps to reproduce

1. Have `publiclist.anchel.nl` down or blocked
2. Launch Mirage

### Proposed Solution

Show a user facing error that it is blocked and/or 1) retry with a timeout or 2) a button to retry.

Edit. The domain was probably taken down sometime after the issue was posted.

**Comment by ghost** [comment]
publiclist.anchel.nl seems to not exist as a domain name?

**Comment by MRAAGH** [comment]
We need to find an equivalent Matrix server list. It needs to have an API, not just a web page

**Comment by MRAAGH** [comment]
Actually, this is related or duplicate of #249
