### ISSUE TITLE
Mirage is Broken on Alpine/PostmarketOS: gives an infinite spinning wheel on startup

### ISSUE THREAD

**Issue by mikebdp2** [mirukana/mirage#276]
Experienced on Pinephone _(so - a smaller screen than Desktop)_

**Comment by MRAAGH** [comment]
Possibly duplicate of #275

You should try [this](https://github.com/mirukana/mirage/issues/275#issuecomment-1000596202) if you haven't yet

**Comment by Newbytee** [comment]
> Possibly duplicate of #275

I think it isn't. I have heard of people experiencing this issue with the Alpine package on the PinePhone before Python 3.10, but I can't reproduce it myself so it's hard to do anything about. Besides, if it was the Python 3.10 issue he'd at least be able to get to the dysfunctional server list.

**Comment by koopa1338** [comment]
I encounter this under arch linux as well. I already tried the fork of @vSLG but that didn't work. I also get some weird error messages if I start the application from the terminal, this might help debugging:

```~ 01:46:08 | Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
! 01:46:08 | QSystemTrayIcon::setVisible: No Icon set
~ 01:46:09 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 181, in <module>\n    BRIDGE = QMLBridge()\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 52, in __init__\n    from .backend import Backend\n\n  File \"qrc:/src/backend/backend.py\", line 37, in <module>\n    from .user_files import (\n\n  File \"qrc:/src/backend/user_files.py\", line 18, in <module>\n    from watchgod import Change, awatch\n\nModuleNotFoundError: No module named 'watchgod'\n"
! 01:46:09 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 181, in <module>
    BRIDGE = QMLBridge()

  File "qrc:/src/backend/qml_bridge.py", line 52, in __init__
    from .backend import Backend

  File "qrc:/src/backend/backend.py", line 37, in <module>
    from .user_files import (

  File "qrc:/src/backend/user_files.py", line 18, in <module>
    from watchgod import Change, awatch

ModuleNotFoundError: No module named 'watchgod'
)
~ 01:46:09 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 01:46:09 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)```

mention me if you need some more information about system etc

**Comment by DrRac27** [comment]
On Arch `python-watchgod` is broken. There is a bug report over here: https://bugs.archlinux.org/task/74650?project=5&string=python-watchgod

If you downgrade everything works as expected.
