### ISSUE TITLE
Startup Crash FreeBSD

### ISSUE THREAD

**Issue by constantinfuerst** [mirukana/mirage#280]
### Welcome
Hello and thanks for taking the time to read this and potentially investigate. My python is far from where it needs to be to solve this so I hope some more experienced folk can chime in. Thanks.

### Description
The manually built version will not launch under FreeBSD. The Qt-Window opens with the mirage loading circle thing but never gets past that. Error report down below. Feel free to ask for any additional information.

### Your environment
- OS: FreeBSD 13
- Arch x86-64
- DE: DWM, X11
- Install by manual Build
- QT5.15.2_2
- Python 3.8

PyOtherSide 1.5.9 from package manager and the rest of the libs too.

### Steps to reproduce
Build under FreeBSD, then start the application.

### Expected behavior
Application Launch.

### Actual behavior
Crash on import in qml_bridge:

``` zsh
❯ mirage
~ 11:40:59 | Got library name:  "/usr/local/lib/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
! 11:41:00 | QSystemTrayIcon::setVisible: No Icon set
~ 11:41:00 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<frozen importlib._bootstrap>\", line 908, in _find_spec\n\nAttributeError: 'PyOtherSideQtRCImporter' object has no attribute 'find_spec'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nImportError: PyCapsule_Import could not import module \"datetime\"\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load_unlocked\n\n  File \"<frozen importlib._bootstrap>\", line 910, in _find_spec\n\n  File \"<frozen importlib._bootstrap>\", line 884, in _find_spec_legacy\n\n  File \"qrc://io/thp/pyotherside/qrc_importer.py\", line 26, in find_module\n\n  File \"qrc://io/thp/pyotherside/qrc_importer.py\", line 38, in get_filename\n\nSystemError: <built-in function qrc_is_file> returned a result with an error set\n"
! 11:41:00 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "<frozen importlib._bootstrap>", line 908, in _find_spec

AttributeError: 'PyOtherSideQtRCImporter' object has no attribute 'find_spec'


During handling of the above exception, another exception occurred:


ImportError: PyCapsule_Import could not import module "datetime"


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 910, in _find_spec

  File "<frozen importlib._bootstrap>", line 884, in _find_spec_legacy

  File "qrc://io/thp/pyotherside/qrc_importer.py", line 26, in find_module

  File "qrc://io/thp/pyotherside/qrc_importer.py", line 38, in get_filename

SystemError: <built-in function qrc_is_file> returned a result with an error set
)
~ 11:41:00 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 11:41:00 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```

**Comment by MRAAGH** [comment]
Is this issue solved?

**Comment by constantinfuerst** [comment]
It is not, however after opening it, I noticed the last activity in the repo was about 9 months ago.
I tried out moment but got the same issue there. Closed it as I did not think anybody to take note.
Please excuse the commentless close, really did not expect any interest ...

**Comment by MRAAGH** [comment]
Seems to be same as https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255766

Probably BSD-specific?
