### ISSUE TITLE
Traceback (most recent call last):   File "qrc:/src/backend/matrix_client.py", line 399, in _start  Problem

### ISSUE THREAD

**Issue by CXXxx3tgui** [mirukana/mirage#286]
### Description

Describe your issue in details, provide error logs or screenshots if possible.

### Your environment

- OS or distribution (e.g. Arch Linux, macOS 10.15, Windows 7...)
Debian GNU/Linux 11 (bullseye)
- Architecture (e.g. x86 64bit)
x86_64
- For Linux users: your desktop environment or window manager (e.g. GNOME 3.34 Wayland, i3 4.17, etc)
XFCE
- How did you install Mirage? (e.g. manual build, distribution repository, AppImage, Flatpak...)
Distribution Repo

### Steps to reproduce

1.Started the program through proxychains
2.Chosen my matrix server
2.Signed into my account
3.Errors popped up from there
4.Purged mirage
5.Reinstalled mirage
6.Used without proxychains
7.Same issue occurs

### Expected behavior

To load up my account when signing in

### Actual behavior
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1130, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1003, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)

**Comment by MRAAGH** [comment]
This might be an issue specific to your account or your server. Could you try to log in to an account on a different server using the same Mirage installation?

**Comment by CXXxx3tgui** [comment]
Tried again with a different account on the matrix.org server, didn't work and came up with the same error

**Comment by z411** [comment]
Having very similar errors as well. Tried on several Synapse and Dendrite homeservers with similar results.

```
Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/tmp/.mount_MirageSwgWfh/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/tmp/.mount_MirageSwgWfh/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1120, in load_past_events
    response = await self.room_messages(
  File "/tmp/.mount_MirageSwgWfh/usr/lib/python3.9/site-packages/nio/client/async_client.py", line 2314, in room_messages
    return await self._send(
  File "qrc:/src/backend/matrix_client.py", line 269, in _send
    raise await MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None, 'unknown error', '{"chunk":[],"start":"t168-1418169_12934182_106955_1661231_131280_195_39376_890478_0"}')
```

I'm using the AppImage v0.7.2 on Void Linux x86_64 glibc.

**Comment by Asherathe** [comment]
> Having very similar errors as well. Tried on several Synapse and Dendrite homeservers with similar results.
> 

I got exactly the same error as z411 today after joining #space:opensuse.org and trying to load old messages.
Loading unread messages from rooms I previously joined works fine. I think this is caused by the lack of Spaces support.

I'm using the AppImage 0.7.2 on OpenSuse Tumbleweed with XFCE.

**Comment by narcisgarcia** [comment]
- Debian GNU/Linux 11/Stable (amd64) +Gnome
- matrix-mirage repository package version 0.11.1-1+b2

```
$ matrix-mirage 
~ 14:40:13 | Got library name:  "/usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
! 14:40:14 | qrc:/src/gui/UI.qml:132:9: Unable to assign [undefined] to QUrl
! 14:40:14 | qrc:/src/gui/Base/HFlickableColumnPage.qml:27:5: QML HFlickable: Binding loop detected for property "contentHeight"
! 14:40:14 | qrc:/src/gui/Base/HAvatar.qml:61:5: QML HMxcImage: Binding loop detected for property "cache"
! 14:40:14 | qrc:/src/gui/Base/HAvatar.qml:61:5: QML HMxcImage: Binding loop detected for property "cache"
! 14:40:14 | qrc:/src/gui/Base/HFlickableColumnPage.qml:27:5: QML HFlickable: Binding loop detected for property "contentHeight"
X 14:40:15 | python: (200, None)
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1130, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1003, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)
```

Application opens and allows subscribing an account, but does not receive communications from contacts.
