### ISSUE TITLE
Warnings and errors on Debian make application unusable

### ISSUE THREAD

**Issue by narcisgarcia** [mirukana/mirage#289]
- Debian GNU/Linux 11/Stable (amd64) +Gnome
- matrix-mirage repository package version 0.11.1-1+b2

```
$ matrix-mirage 
~ 14:40:13 | Got library name:  "/usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
! 14:40:14 | qrc:/src/gui/UI.qml:132:9: Unable to assign [undefined] to QUrl
! 14:40:14 | qrc:/src/gui/Base/HFlickableColumnPage.qml:27:5: QML HFlickable: Binding loop detected for property "contentHeight"
! 14:40:14 | qrc:/src/gui/Base/HAvatar.qml:61:5: QML HMxcImage: Binding loop detected for property "cache"
! 14:40:14 | qrc:/src/gui/Base/HAvatar.qml:61:5: QML HMxcImage: Binding loop detected for property "cache"
! 14:40:14 | qrc:/src/gui/Base/HFlickableColumnPage.qml:27:5: QML HFlickable: Binding loop detected for property "contentHeight"
X 14:40:15 | python: (200, None)
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1130, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1003, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (200, None)
```

Application opens and allows subscribing an account, but does not receive communications from contacts.

**Comment by MRAAGH** [comment]
Possibly an old bug. Mirage is unmaintained. You should try https://mx-moment.xyz
