### ISSUE TITLE
Unhandled "Internal Server Error"

### ISSUE THREAD

**Issue by igel-kun** [mirukana/mirage#291]
### Description

Mirage tells me that an "Unexpected error occured":
```MatrixError: @<username>:matrix.tu-berlin.de.get_offline_presence.b1d3909c-6dac-48f9-a10b-01afbc9407d4

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1572, in get_offline_presence
    resp = await self.get_presence(user_id)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 284, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 2878, in get_presence
    return await self._send(
  File "qrc:/src/backend/matrix_client.py", line 269, in _send
    raise await MatrixError.from_nio(response)
backend.errors.MatrixError: (500, 'M_UNKNOWN', 'Internal server error', '{"errcode":"M_UNKNOWN","error":"Internal server error"}')
```

### Your environment

Ubuntu 22.04, x86_64, enlightenment E25, installed via apt-get (distribution package)

### Steps to reproduce

1. Go to a room with plenty of participants on my universitie's matrix server (which may be a bit flaky at times)

### Expected behavior

I suppose the error should be handled

### Actual behavior

An unhandled error occured

**Comment by MRAAGH** [comment]
for an error like this, since it came from the remote server, I'd almost say the best way to handle it is to display it to the user, so they can know exactly what's happening
