### ISSUE TITLE
`AttributeError` when trying to import E2E room keys

### ISSUE THREAD

**Issue by jodizzle** [mirukana/mirage#34]
When trying to import the E2E room keys, I get this error after a few seconds:
```
Traceback (most recent call last):
  File "src/backend/qml_bridge.py", line 78, in on_done
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "src/backend/matrix_client.py", line 1051, in import_keys
    await self.retry_decrypting_events()
  File "src/backend/matrix_client.py", line 1094, in retry_decrypting_events
    await asyncio.coroutine(cb.func)(room, decrypted)
  File "src/backend/nio_callbacks.py", line 108, in onRoomMessageText
    await self.client.register_nio_event(
  File "src/backend/matrix_client.py", line 1311, in register_nio_event
    model[item.id] = item
  File "src/backend/models/model.py", line 82, in __setitem__
    setattr(existing, field, getattr(new, field))
  File "src/backend/models/model_item.py", line 51, in __setattr__
    self.serialize_field(name),
  File "src/backend/models/items.py", line 227, in serialize_field
    source_dict = nio.attr.asdict(self.source) if self.source else {}
AttributeError: module 'nio' has no attribute 'attr'
```
I get this error (or very similar, file paths might be slightly different) on both the Arch Linux AUR installation of Mirage and a manual installation.

The problem seems to be caused by newer versions of the matrix-nio package.  Installing a slightly older version, v0.10.0, from the upstream repo like so
```
pip install "git+git://github.com/poljar/matrix-nio.git@0.10.0#egg=matrix-nio[e2e]"
```
seems to fix the issue.

**Comment by CodedBinary** [comment]
Also got AttributeError on archlinux X+i3wm downloaded through AUR/ After a fresh download, trying to read a chat message didn't work. The chat messages didn't load, and the downgrade fixed it.

**Comment by mirukana** [comment]
Added a workaround for this in https://github.com/mirukana/mirage/commit/4bae3cf90e49c75d4bf986c235780a4faee9c744, can you confirm things work as expected after reinstalling/updating the AUR package? It should pull directly from master if I remember correctly.

**Comment by jodizzle** [comment]
@mirukana That seems to have fixed it.  I'm no longer seeing this problem in the manual installation or the AUR installation.  Thanks.
