### ISSUE TITLE
TypeError when trying to import decryption keys

### ISSUE THREAD

**Issue by raffomania** [mirukana/mirage#50]
I exported my decryption keys using the riot web interface, but get the following error when trying to import them:
```
Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 82, in on_done
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1151, in import_keys
    await self.retry_decrypting_events()
  File "qrc:/src/backend/matrix_client.py", line 1179, in retry_decrypting_events
    for ev in deepcopy(model).values():
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object
```
Fresh install on Arch Linux, python 3.8.3, mirage 0.5.0

**Comment by adri326** [comment]
Same thing here, exported my keys minutes ago and tried importing them. The error showed up after a minute or two of loading.

**Comment by mirukana** [comment]
https://github.com/mirukana/mirage/commit/60fa027c2e8552eb757230bfef136c9b1c63d912 should fix the issue, can you confirm?

**Comment by raffomania** [comment]
Awesome, works on my machine, thanks for the quick fix and for mirage in general, I love it!
