### ISSUE TITLE
Can't send message in encrypted room

### ISSUE THREAD

**Issue by ellietheoracle** [mirukana/mirage#79]
### Description

```
@theotheroracle:the-apothecary.club.send_text.996c4224-c2d5-468f-a633-5658646a178c

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 82, in on_done
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 454, in send_text
    await self._send_message(room_id, content, tx_id)
  File "qrc:/src/backend/matrix_client.py", line 773, in _send_message
    ignore_unverified_devices = True,
  File "/app/lib/python3.7/site-packages/nio/client/async_client.py", line 1481, in room_send
    room_id, message_type, content
  File "/app/lib/python3.7/site-packages/nio/client/base_client.py", line 116, in inner
    return fn(self, *args, **kwargs)
  File "/app/lib/python3.7/site-packages/nio/client/base_client.py", line 1160, in encrypt
    "The room is encrypted and the members " "aren't fully synced."
nio.exceptions.MembersSyncError: The room is encrypted and the members aren't fully synced.
```

### Your environment

flatpak, fedora

**Comment by ellietheoracle** [comment]
when clearing the room:

```
@theotheroracle:the-apothecary.club.get_event_profiles.03df89c1-872a-4dec-8318-0c3690ebe93e

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 82, in on_done
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1413, in get_event_profiles
    ev: Event = self.models[self.user_id, room_id, "events"][event_id]
  File "qrc:/src/backend/models/model.py", line 72, in __getitem__
    return self._data[key]
KeyError: 
```

**Comment by ellietheoracle** [comment]
clearing the room doesn't fix the issue, i'm not sure what's causing it .

**Comment by vSLG** [comment]
Isn't this the same as #54?

**Comment by ellietheoracle** [comment]
i think so, yeah .
