### ISSUE TITLE
MatrixBadGateway

### ISSUE THREAD

**Issue by ellietheoracle** [mirukana/mirage#96]
### Description

```


Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/nio/client/async_client.py", line 956, in sync
    timeout,
  File "qrc:/src/backend/matrix_client.py", line 213, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixBadGateway
```

### Your environment

- flatpak ( compiled manually )

### Steps to reproduce

a lot of messages were being received at the time, might have been the cause of it .

**Comment by mirukana** [comment]
Need to make nio catch and handle HTTP 5xx errors.

**Comment by JanZerebecki** [comment]
Probably the same for 408:
```
Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 399, in _start
    await self.sync_task
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 1147, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.9/asyncio/tasks.py", line 611, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3/dist-packages/nio/client/async_client.py", line 994, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (408, None)
```
Debian packages:
Mirage: 0.6.4~dfsg+~hsluv1.0.0-4
nio: 0.15.2-1
